notifications_page:
  path: /notifications
  defaults: {  _controller: AppBundle:Notification:index }

notifications_count:
  path: /notifications/get
  defaults: {  _controller: AppBundle:Notification:countNotifications }