login:
  path: /login
  defaults: { _controller: AppBundle:User:login }
  methods: GET

## a estas dos no le hago methods y default, porque apunto a una funcion que symfony me hace solo 
login_check:
  path: /login_check

logout:
  path: /logout

register:
  path: /register
  defaults: { _controller: AppBundle:User:register }

nick_test:
  path: /nick-test
  defaults: { _controller: AppBundle:User:nickTest }
  methods: ["POST"]

user_edit:
  path: /my-data
  defaults: { _controller: AppBundle:User:editUser }

user_list:
  path: /people
  defaults: { _controller: AppBundle:User:users }

user_search:
  path: /search
  defaults: { _controller: AppBundle:User:search }