login:
  path: /login
  defaults: { _controller: AppBundle:User:login }
  methods: GET

register:
  path: /register
  defaults: { _controller: AppBundle:User:register }
  methods: ["GET", "POST"]

nick_test:
  path: /nick-test
  defaults: { _controller: AppBundle:User:nickTest }
  methods: ["POST"]